CREATE TABLE "proposals" (
	"id" serial PRIMARY KEY NOT NULL,
	"packageName" text,
	"clientName" text NOT NULL,
	"departureDate" text NOT NULL,
	"returnDate" text NOT NULL,
	"adults" integer DEFAULT 2 NOT NULL,
	"children" integer DEFAULT 0 NOT NULL,
	"childrenAges" text,
	"days" integer,
	"nights" integer,
	"coverImageUrl" text,
	"hotelName" text,
	"hotelPhotos" text,
	"includedItems" text NOT NULL,
	"pricePerPerson" integer NOT NULL,
	"totalPrice" integer NOT NULL,
	"downPayment" integer NOT NULL,
	"installments" integer NOT NULL,
	"installmentValue" integer NOT NULL,
	"firstInstallmentDate" text,
	"installmentDates" text NOT NULL,
	"phoneNumber" text,
	"email" text,
	"instagramUrl" text,
	"createdBy" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"viewedAt" timestamp,
	"approvedAt" timestamp,
	"expiresAt" timestamp,
	"viewCount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"openId" text NOT NULL,
	"name" text,
	"email" text,
	"loginMethod" text,
	"role" text DEFAULT 'user' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
